{% set version = '0.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gpseq
  version: {{ version|replace("-", "_") }}

source:
  url:     {{ cran_mirror }}/src/contrib/Archive/GPseq/GPseq_{{ version }}.tar.gz
  sha256: 5121b6a4723efbe91a6a86074a100c383257a1ee2628e9d9be574c4c888bbd4c

build:
  merge_build_host: True  # [win]
  number: 1004
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('GPseq')"           # [not win]
    - "\"%R%\" -e \"library('GPseq')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GPseq
  license: GPL-2.0-only
  summary: Some functions for modeling sequence read counts as a generalized poisson model and
    to use this model for detecting differentially expressed genes in different conditions
    and differentially spliced exons.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: GPseq
# Type: Package
# Title: gpseq: Using the generalized Poisson distribution to model sequence read counts from high throughput sequencing experiments
# Version: 0.5
# Date: 2011-01-10
# Author: Sudeep Srivastava, Liang Chen
# Maintainer: Sudeep Srivastava <sudeepsr@usc.edu>
# Description: Some functions for modeling sequence read counts as a generalized poisson model and to use this model for detecting differentially expressed genes in different conditions and differentially spliced exons.
# Depends: R (>= 2.10.1)
# License: GPL-2
# LazyLoad: yes
# Packaged: 2011-07-05 17:11:05 UTC; sudeepsr
# Repository: CRAN
# Date/Publication: 2011-07-06 18:55:51
