# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "OK4IKLUuzCH9xxBvr/GB/wTYTT4kyY2ExKKNoAQNGeF3hUPb4RZ4v0yo1ilio4xPLOP3uoAmzPcfGFp91jlPwRsKw0z9wYTQpWmVMKOO/6KEqFBsfsdb5YmLZQQVkICoIcRr9adxS0sPnKkYkq+w5OdB7uqve3apKgJxRoEkAAUnpNJJ3ihk9YCkHOynGGUX6B/SdJ9VMcZo08RFEBIXgp1U4cLF22nnZUhqMklqOQZtM/suPYChXmLZYsJGC2V5n0Q2E57R4rtwVj5aLiUQB6Q/bwgherR1po2IuB8HgWVvBgFaEFDGufz/MOHGdgTUVCm+5tB4DW0oeNDNpzfW1th/EmMDTR3SanAkrRKPeOtDfSd04JKqsfFzTDrG/BXNbMfrWsKU8mHqKOyBgumgVIeZB7WaXpx5MjtTgLZPDFi/9teKkwNMJYqBAhCGignA8BOFm/jAQDNes/9Pq1+L/ch0GbywVHYeQ4QHVft3OwKzmD6Pum1364acCLH80KFqcpmsd+RnnNIqwf+ePAHFZw55S1do1I9UQaj/72pmNRy7yaaAXEZi5NZEciCqKdsTGwUTO/83DPLzTOIn85RQ30zngFe8TzbJNq9jYp7vDCxapJa4nkviA5VMsODNsg0Ptq1kN6mtSjpv2zST+qnMDFNNhCXoGXcRSXw3aKSLlyc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
