appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OK4IKLUuzCH9xxBvr/GB/wTYTT4kyY2ExKKNoAQNGeF3hUPb4RZ4v0yo1ilio4xPLOP3uoAmzPcfGFp91jlPwRsKw0z9wYTQpWmVMKOO/6KEqFBsfsdb5YmLZQQVkICoIcRr9adxS0sPnKkYkq+w5OdB7uqve3apKgJxRoEkAAUnpNJJ3ihk9YCkHOynGGUX6B/SdJ9VMcZo08RFEBIXgp1U4cLF22nnZUhqMklqOQZtM/suPYChXmLZYsJGC2V5n0Q2E57R4rtwVj5aLiUQB6Q/bwgherR1po2IuB8HgWVvBgFaEFDGufz/MOHGdgTUVCm+5tB4DW0oeNDNpzfW1th/EmMDTR3SanAkrRKPeOtDfSd04JKqsfFzTDrG/BXNbMfrWsKU8mHqKOyBgumgVIeZB7WaXpx5MjtTgLZPDFi/9teKkwNMJYqBAhCGignA8BOFm/jAQDNes/9Pq1+L/ch0GbywVHYeQ4QHVft3OwKzmD6Pum1364acCLH80KFqcpmsd+RnnNIqwf+ePAHFZw55S1do1I9UQaj/72pmNRy7yaaAXEZi5NZEciCqKdsTGwUTO/83DPLzTOIn85RQ30zngFe8TzbJNq9jYp7vDCxapJa4nkviA5VMsODNsg0Ptq1kN6mtSjpv2zST+qnMDFNNhCXoGXcRSXw3aKSLlyc=}
bot:
  automerge: true
